# Generated by Django 5.2.7 on 2025-10-18 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-disponible', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('dobles', 'Dobles'), ('mixto', 'Mixto')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada'), ('Apartada', 'Apartada'), ('Mantenimiento', 'Mantenimiento')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('reservada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Canchas',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('victorias', models.PositiveIntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
            },
        ),
    ]
