# Generated by Django 5.2.7 on 2025-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={},
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='reservada_por',
        ),
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canchas/'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo',
            field=models.CharField(choices=[('padel', 'Padel'), ('tenis', 'Tenis')], default='padel', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancha',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('mantenimiento', 'Mantenimiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
    ]
