# Generated by Django 5.2.7 on 2025-10-18 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cancha_options_remove_cancha_reservada_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('juvenil', 'Juvenil'), ('adulto', 'Adulto'), ('senior', 'Senior')], max_length=50)),
                ('ranking', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('biografia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
                'ordering': ['-ranking'],
            },
        ),
        migrations.AlterModelOptions(
            name='cancha',
            options={'verbose_name_plural': 'Canchas'},
        ),
        migrations.AlterModelOptions(
            name='torneo',
            options={'ordering': ['fecha_inicio'], 'verbose_name_plural': 'Torneos'},
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Hombre Menor', 'Hombre Menor'), ('Mujer Menor', 'Mujer Menor')], default='Hombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneo',
            name='jugadores_inscritos',
            field=models.ManyToManyField(blank=True, related_name='torneos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torneo',
            name='premios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
