# Generated by Django 5.2.7 on 2025-10-19 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jugador_alter_cancha_options_alter_torneo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('marcador', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('arbitro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_arbitrados', to=settings.AUTH_USER_MODEL)),
                ('cancha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cancha')),
                ('jugadores', models.ManyToManyField(related_name='partidos_jugados', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='core.torneo')),
            ],
            options={
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cancha')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservas de Canchas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
