# Generated by Django 5.2.7 on 2025-10-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_torneo_arbitro_partido_reservacancha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
